### PR TITLE
[FIF-225] Convert Student Detail to React

### PR DESCRIPTION
**Pull request by kurtjohnson-HS**
This task is to update the Student Detail to use a React component.

### CODE REVIEW

**Comment by DavidJGapCR** [comment]
In general it looks great! I see some small issues related to the responsiveness of the page. Attaching screenshot.

**Comment by DavidJGapCR** [comment]
Should we show a confirmation pop up when the user wants to delete a note?

**Comment by jleiva-gap** [comment]
> 
> 
> In general it looks great! I see some small issues related to the responsiveness of the page. Attaching screenshot.
> 
> 

It also happens in notes

**Comment by DavidJGapCR** [comment]
In previous translations we deleted the angular component. I think in this case we can delete it as well, in this case **StudentDetailComponent**. Unless you see a reason to keep it, of course.

**Comment by DavidJGapCR** [comment]
I just got latest and when I run the app I get this error:

```
app/Features/StudentDetailReact/StudentDetailNotesContainer.tsx:88:28 - error TS2339: Property 'staffEMail' does not exist on type 'string'.

88               newNote.note.staffEMail = author.electronicmailaddress;
```

**Comment by DavidJGapCR** [comment]
I found another issue, it looks like the drop down menu disappeared.

**Comment by NSD-Xavier** [comment]
Lint issues (" -> ')

**Pull request merged**
