### PR TITLE
[FIF-287] Created an error boundary 

### PR DESCRIPTION
**Pull request by jleiva-gap**
1. Select one of the components, for example StudentDetail.
2. Add an exception in StudentDetail, to test the ErrorBoundary.
Capture

3. On the screen where the component is used, put it inside the ErrorBoundary.
`<ErrorBoundary><StudentDetail></StudentDetail></ErrorBoundary>`

4. Run the application in production mode. If you run it with the development version, the error screen will be displayed.
`yarn start-prod -p 4200`

5. It should display the error message.
Capture2

### CODE REVIEW

**Review by kurtjohnson-HS — CHANGES_REQUESTED** [review]
Warning looks good!

I was also expecting to surround our App component with this, so that any errors bubbling up to the top-most App parent will be captured. This also prevents the React "white-screen of death".

**Comment by kurtjohnson-HS** [comment]
> > Warning looks good!
> > I was also expecting to surround our App component with this, so that any errors bubbling up to the top-most App parent will be captured. This also prevents the React "white-screen of death".
> 
> @kurtjohnson-HS , I updated index.ts to add this change.
> 
> `ReactDOM.render(<ErrorBoundary><App /></ErrorBoundary>, document.getElementById('root'));`

Looks good. It only needs a yarn lint to pass the build and we should merge it. For me this is approved pending the lint.

**Review by kurtjohnson-HS — CHANGES_REQUESTED** [review]
It just needs a lint then it should be approved.

**Comment by kurtjohnson-HS** [comment]
One more thing... Can you do a rebase so that all of these file changes disappear? I am concerned that we might overwrite some master changes with merge changes.

**Comment by jleiva-gap** [comment]
> 
> 
> One more thing... Can you do a rebase so that all of these file changes disappear? I am concerned that we might overwrite some master changes with merge changes.

I rebased the branch. I fixed the linting issues in ErrorBoundary.

**Comment by kurtjohnson-HS** [comment]
Above, it still shows the PR will change 31 files. It only looks like it should change five. Your last commit looks like a merge and not a rebase. Can you rebase again? I know that you will have to resolve the yarn.lock and package.json.

**Review by kurtjohnson-HS — CHANGES_REQUESTED** [review]
Needs a rebase to just show five file changes.

**Comment by NSD-Xavier** [comment]
How about adding an email for support in  `... contact support if the error keeps happening`. it can be configured in .env

**Comment by jleiva-gap** [comment]
> 
> 
> Needs a rebase to just show five file changes.

I rebased this branch before pushing my changes (3 files). After I rebased the branch those 31 files appeared. I have not modified those files, they are the ones that come from main. I didn't merge main into FIF-287.

**Pull request closed without merging**
