### PR TITLE
[FIF-307] Added the header and footer in React

### PR DESCRIPTION
**Pull request by jleiva-gap**
image

Responsive
image

### CODE REVIEW

**Review by kurtjohnson-HS — CHANGES_REQUESTED** [review]
This looks fantastic. 

I just see a couple of potential fixes.
- Can you move the footer flush with the bottom? It looks like there is space underneath.
- There is some horizontal scrolling on the student roster in the narrow media query width. Can you look at the containers to see where we are too wide?

image

- The drop down for the name might need some sizing changes
image

**Comment by NSD-Xavier** [comment]
Looks awesome.

* Icons missing from menu
  image

* Options looks not vertically centered

* When I scroll up, the footer scrolls and half hide
  image

**Comment by jleiva-gap** [comment]
I updated this branch to include PR comments.
@kurtjohnson-HS , I fixed the position and width of the footer. The screen overflow is due to a style in the row of student roster, I think a bug should be create to fix it.

**Comment by jleiva-gap** [comment]
I updated this branch to include PR comments.
@kurtjohnson-HS , I fixed the position and width of the footer. The screen overflow is due to a style in the row of student roster, I think a bug should be create to fix it.

**Comment by kurtjohnson-HS** [comment]
> I updated this branch to include PR comments.
> @kurtjohnson-HS , I fixed the position and width of the footer. The screen overflow is due to a style in the row of student roster, I think a bug should be create to fix it.

I still see some space and text showing. On the topic of the student roster, I created a bug to fix and put it in sprint planning.

image

**Review by kurtjohnson-HS — CHANGES_REQUESTED** [review]
I am still seeing the footer not flush to the bottom.

image

**Comment by NSD-Xavier** [comment]
Header is hiding student label and count
- Displays
  image
- Should be
  image

**Comment by jleiva-gap** [comment]
> 
> 
>     * Header is hiding student label and count
>       
>       * Displays
>         image
>       * Should be
>         image
**Fixed**
> 
>     * Footer overlaps student card
>       
>       * Displays
>         image
>       * Should be
>         image
**Fixed**
> 
>     * Seems to have extra space to the right. It allows to horizontally scroll the card list
**It's a style on Student Roster. We should fix it in another ticket**

**Review by kurtjohnson-HS — APPROVED** [review]

**Pull request merged**
