### PR TITLE
Fif 293

### PR DESCRIPTION
**Pull request by OscarSarabiaNSD**
I removed the old Angular project from the repository.
    I Removed the teamcity Angular build folder, and the angular.AngularProject subproject from the .teamcity_Self\Project.kt file.
    resolve any outdated documentation referring to the Angular project.

### CODE REVIEW

**Comment by NSD-Xavier** [comment]
Main readme (`EdFi-Project-Buzz/README.md`) have references to the angular project

**Comment by NSD-Xavier** [comment]
- `.teamcity\_Self\Project.kt` have references to angular (`subProject(angular.AngularProject)`)
- `EdFi.Buzz.Api\yarn.lock` have a lot of angular references. Do we need angular in this project?

**Comment by OscarSarabiaNSD** [comment]
> 
> 
>     * `.teamcity\_Self\Project.kt` have references to angular (`subProject(angular.AngularProject)`)
> 
>     * `EdFi.Buzz.Api\yarn.lock` have a lot of angular references. This is because it's a dependency of
>       
>       * `"@nestjs/cli": "^7.0.0",`
>       * `"@nestjs/schematics": "^7.0.0",`

planning to remove the references from all the files you are commenting now but  on FIF-301 task

**Review by NSD-Xavier — APPROVED** [review]

**Comment by NSD-Xavier** [comment]
- TeamCity errors may be because yarn.lock files are deleted. You can run yarn install in each project to re-create these files.
- Also, for the api project, "@nestjs/graphql > @nestjs/mapped-types@0.1.0" needs "class-transformer@^0.3.0" and we have "0.2.3" package.json.

**Review by NSD-Xavier — APPROVED** [review]

**Pull request merged**
