### PR TITLE
[FIF-349] Move upload surveys to inside of survey administration

### PR DESCRIPTION
**Pull request by jleiva-gap**
image

### CODE REVIEW

**Comment by DavidJGapCR** [comment]
@david-clements-ed-fi I have doubts with this ticket.
If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
Does it make sense?
I am missing something and not seeing this correctly?

**Comment by david-clements-ed-fi** [comment]
> @david-clements-ed-fi I have doubts with this ticket.
> If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
> Does it make sense?
> I am missing something and not seeing this correctly?

Let me iterate through the scenarios and the behavior I'm expecting.  Let me know if I'm off somewhere.

1. **teacher with no survey access** - This user would not see the upload survey or survey admin links in the old configuration.  They would also not have access to either in the new configuration.
1. **teacher with survey access** - This user would see the upload survey option (to add their own surveys) and the survey admin link so they could update and delete their own surveys in the old configuration.  In the new configuration, they would have access to the survey admin screen to see their existing survey's and the upload link would live within to add new surveys.  The scope of surveys to see would remain the same in both configurations.  This user could only see their own surveys they added.
1.  **admin access** - This would would see the upload and survey admin screen in the old configuration.  In the new configuration, they would see the survey admin menu and the upload survey administration would be inside the survey administration.  This user would see all the surveys in their admin page because they are of type admin.

Did I miss something because I don't see a change in behavior or access?

**Comment by DavidJGapCR** [comment]
> > @david-clements-ed-fi I have doubts with this ticket.
> > If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
> > Does it make sense?
> > I am missing something and not seeing this correctly?
> 
> Let me iterate through the scenarios and the behavior I'm expecting. Let me know if I'm off somewhere.
> 
> 1. **teacher with no survey access** - This user would not see the upload survey or survey admin links in the old configuration.  They would also not have access to either in the new configuration.
> 2. **teacher with survey access** - This user would see the upload survey option (to add their own surveys) and the survey admin link so they could update and delete their own surveys in the old configuration.  In the new configuration, they would have access to the survey admin screen to see their existing survey's and the upload link would live within to add new surveys.  The scope of surveys to see would remain the same in both configurations.  This user could only see their own surveys they added.
> 3. **admin access** - This would would see the upload and survey admin screen in the old configuration.  In the new configuration, they would see the survey admin menu and the upload survey administration would be inside the survey administration.  This user would see all the surveys in their admin page because they are of type admin.
> 
> Did I miss something because I don't see a change in behavior or access?

It makes sense. I think we need a change in the code to have the survey admin screen available for the teachers with survey access. I may be wrong but I think this menu options is shown to admins only right now.

**Comment by david-clements-ed-fi** [comment]
> > > @david-clements-ed-fi I have doubts with this ticket.
> > > If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
> > > Does it make sense?
> > > I am missing something and not seeing this correctly?
> > 
> > 
> > Let me iterate through the scenarios and the behavior I'm expecting. Let me know if I'm off somewhere.
> > 
> > 1. **teacher with no survey access** - This user would not see the upload survey or survey admin links in the old configuration.  They would also not have access to either in the new configuration.
> > 2. **teacher with survey access** - This user would see the upload survey option (to add their own surveys) and the survey admin link so they could update and delete their own surveys in the old configuration.  In the new configuration, they would have access to the survey admin screen to see their existing survey's and the upload link would live within to add new surveys.  The scope of surveys to see would remain the same in both configurations.  This user could only see their own surveys they added.
> > 3. **admin access** - This would would see the upload and survey admin screen in the old configuration.  In the new configuration, they would see the survey admin menu and the upload survey administration would be inside the survey administration.  This user would see all the surveys in their admin page because they are of type admin.
> > 
> > Did I miss something because I don't see a change in behavior or access?
> 
> It makes sense. I think we need a change in the code to have the survey admin screen available for the teachers with survey access. I may be wrong but I think this menu options is shown to admins only right now.

That makes sense.  @jleiva-gap, Can you verify what the code is doing and then add a ticket if the a teacher is unable to see the survey administration page?

**Comment by jleiva-gap** [comment]
> 
> 
> > > > @david-clements-ed-fi I have doubts with this ticket.
> > > > If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
> > > > Does it make sense?
> > > > I am missing something and not seeing this correctly?
> > > 
> > > 
> > > Let me iterate through the scenarios and the behavior I'm expecting. Let me know if I'm off somewhere.
> > > 
> > > 1. **teacher with no survey access** - This user would not see the upload survey or survey admin links in the old configuration.  They would also not have access to either in the new configuration.
> > > 2. **teacher with survey access** - This user would see the upload survey option (to add their own surveys) and the survey admin link so they could update and delete their own surveys in the old configuration.  In the new configuration, they would have access to the survey admin screen to see their existing survey's and the upload link would live within to add new surveys.  The scope of surveys to see would remain the same in both configurations.  This user could only see their own surveys they added.
> > > 3. **admin access** - This would would see the upload and survey admin screen in the old configuration.  In the new configuration, they would see the survey admin menu and the upload survey administration would be inside the survey administration.  This user would see all the surveys in their admin page because they are of type admin.
> > > 
> > > Did I miss something because I don't see a change in behavior or access?
> > 
> > 
> > It makes sense. I think we need a change in the code to have the survey admin screen available for the teachers with survey access. I may be wrong but I think this menu options is shown to admins only right now.
> 
> That makes sense. @jleiva-gap, Can you verify what the code is doing and then add a ticket if the a teacher is unable to see the survey administration page?

I am reviewing the filters on the AdminSurvey page to determine if we also need to modify them.

**Comment by jleiva-gap** [comment]
> 
> 
> > > > @david-clements-ed-fi I have doubts with this ticket.
> > > > If you remember, we have 3 types of users: regular teacher, administrator and teacher who can upload surveys (this is basically defined with flag columns in the staff table). This survey administration page is not accessible to the last user type (teacher who can upload surveys). This means that we are essentially ending up with just 2 user types now.
> > > > Does it make sense?
> > > > I am missing something and not seeing this correctly?
> > > 
> > > 
> > > Let me iterate through the scenarios and the behavior I'm expecting. Let me know if I'm off somewhere.
> > > 
> > > 1. **teacher with no survey access** - This user would not see the upload survey or survey admin links in the old configuration.  They would also not have access to either in the new configuration.
> > > 2. **teacher with survey access** - This user would see the upload survey option (to add their own surveys) and the survey admin link so they could update and delete their own surveys in the old configuration.  In the new configuration, they would have access to the survey admin screen to see their existing survey's and the upload link would live within to add new surveys.  The scope of surveys to see would remain the same in both configurations.  This user could only see their own surveys they added.
> > > 3. **admin access** - This would would see the upload and survey admin screen in the old configuration.  In the new configuration, they would see the survey admin menu and the upload survey administration would be inside the survey administration.  This user would see all the surveys in their admin page because they are of type admin.
> > > 
> > > Did I miss something because I don't see a change in behavior or access?
> > 
> > 
> > It makes sense. I think we need a change in the code to have the survey admin screen available for the teachers with survey access. I may be wrong but I think this menu options is shown to admins only right now.
> 
> That makes sense. @jleiva-gap, Can you verify what the code is doing and then add a ticket if the a teacher is unable to see the survey administration page?

I can add the teacher's permission to see adminsurveys in this same ticket since I have to remove the other option from the menu, the ETL is the one that validates that it can only load surveys from its sections if it does not have the administrator option enabled. Does that make sense to you?

**Comment by david-clements-ed-fi** [comment]
> 
> I can add the teacher's permission to see adminsurveys in this same ticket since I have to remove the other option from the menu, the ETL is the one that validates that it can only load surveys from its sections if it does not have the administrator option enabled. Does that make sense to you?

That makes sense to me.   admin surveys can be visible if the teacher has isteachersurveyloader enabled.

**Comment by DavidJGapCR** [comment]
When I activate the **isteachersurveyloader** flag and disable **isadminsurveyloader**, the menu option is shown, but when I click on it the app says: "Need survey admin rights". I think we need to enable the UI route.

**Review by DavidJGapCR — APPROVED** [review]

**Pull request merged**
